# Generated by Django 4.1.5 on 2023-01-29 21:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_customer', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('CPF', models.CharField(max_length=11)),
                ('phone_number', models.CharField(max_length=14)),
                ('gender', models.CharField(max_length=255)),
                ('CEP', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
